---
title: "회귀분석"
output:
  html_document:
    toc: true
    toc_float: true
    keep_md: true
date: '2022-06-24'
---



## 복습
- 통계 검정
 + 평균 차이 검정: 수치데이터 + 범주데이터(두 그룹)
  - 분산분석 : 세 그룹 이상 평균차이검정 (중급이상)
 + 비율 차이 검정: 범주데이터
 + 상관관계: 수치데이터 
 + 회귀 
 
- 통계 검정 사전 준비
 + 분석을 위한 데이터가 적절한지 검정
 +등분산 검정, 수치 데이터가 정규분포를 이루는가(정규성검증
  )
 
- 귀무가설, 대립가설 적절하게 설정
  + 예)서울의 평균임금과 부산의 평균임금이 차이가 있을것이다.
  + 선행연구(논문찾아서 응용)
  
- 테스트
 + t.test, chisq.test, cor.test
 + p.value
  - p.value > 0.05 --> 귀무가설지지
  - p.value < 0.05 --> 대립가설지지


## 회귀의 중요성
- 기초통계: 특정한 결과에 영향을 주는 요인이 무엇인가를 찾는 것이 회귀
- 회귀분석과 종류
 + 1세대 회귀방법론: 다항회귀분석, 다중회귀분석, 포아송 회귀분석, ect
 + 2세대 회귀방법론: 구조방정식
 
- 귀무가설 & 대립가설 존재
 + 귀무가설: x(독립변수)가 y(종속변수)에 영향을 주지 않는다
 + 대립가설: x(독립변수)가 y(종속변수)에 영향을 준다
 
- 머신러닝, 인공지능
 + 주 목적은 예측 
 + y = ax + b 에서 출발
 
- lm (종속변수 ~ 독립변수, data)
 + p.value 
 

```r
RA <- lm(data=mtcars, mpg~disp)
summary(RA)
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8922 -2.2022 -0.9631  1.6272  7.2305 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 29.599855   1.229720  24.070  < 2e-16 ***
## disp        -0.041215   0.004712  -8.747 9.38e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.251 on 30 degrees of freedom
## Multiple R-squared:  0.7183,	Adjusted R-squared:  0.709 
## F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10
```
 
실제로는 이렇게 깔끔하게 안나온다

 
- ANOVA (분산분석)

식1 : y = disp + var1 + var2 + var3 ….

식2 : y  = disp + var1 + var2 ….

컬럼갯수가 100개 라면 100개를 위와 같이 해야 한다 

컬램갯수를 다 사용하는 것은 아니므로 선별해야 한다


-전진소거법, 후진소거법
 
- Multiple R-squared:  0.7183,	Adjusted R-squared:  0.709
 + R-squared 결정계수 (=설명력) 
 + 범위 0 - 1
 + 1로 수렴할수록 설명력이 좋다
 

 
 
 
 
 
 








